baseurl = "https://www.codeyellow.nl/"
languageCode = "en-us"
title = "Code Yellow BV"
theme = "cy-creative"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Code Yellow BV"
	description = "Creating software to empower your business. Made in Eindhoven."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Code Yellow BV"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			technology = "Technology"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Code Yellow"
		subtitle   = "Software Development"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We Create Software"
		description = "Code Yellow is a business focused on the long term. We strongly believe in giving creative freedom to a group of brilliant people to create innovative concepts and grow them into viable products."
		# description = "We Create Software"
		# buttonText  = "We Create Software"


	# Service section
	[params.services]
		headline = "Our bespoke Back Office Software empowers businesses in various markets"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Direct Marketing"
            description = "Software created specifically to manage new subscriptions, improve subscriber data quality and support various (tele)marketing activities."

        [[params.services.list]]
            icon = "fa-cubes"
            title = "Production"
            description = "Specific tools to manage your product specifications and corresponding production planning as a complete back-office software solution."

        [[params.services.list]]
            icon = "fa-heart"
            title = "HealthCare"
            description = "Easy to use applications, supporting day to day activities of HealthCare employees in the field and improving medication safety."
      
        [[params.services.list]]
			icon = "fa-truck"
			title = "Logistics"
			description = "Logistics software, designed for ease of use and focused on supporting the logistical planning process."


	#[params.technology]
	#	headline = "At Code Yellow we share our technology with other developers"

	#	[[params.technology.list]]
    #        icon = "fa-code"
    #        title = "Open Source"
    #        description = "Code Yellow actively supports the Open Source community and promotes the Open Source philosophy by making our own work available as Open Source libraries. You can find our Open Source projects at both Github and Bitbucket. Visit the repositories and contribute. A small selection of our open source components"

    #    [[params.technology.list]]
    #        icon = "fa-cubes"
    #        title = "Production"
    #        description = "Specific tools to manage your product specifications and corresponding production planning as a complete back-office software solution."



    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "Contact Us about your Software Strategy
	#
	#	[params.aside.button]
	#		text = "Download now"
	#		link = "//github.com/digitalcraftsman/hugo-creative-theme"

	
	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+31 40 780 5090"
		email = "contact@codeyellow.nl"
		irc = "IRC channel #codeyellow on Freenode"
		address = "Torenallee 26-22, 5617 BD  Eindhoven"

	
	#Google Maps section
	[params.location]
		latitude  = "51.44642"
		longitude = "5.459164"
	 	maps_api_key = "AIzaSyAAkG4YMvdPcg-S6nCuGkGvarv2AyYSl0c"